import math
from digital_organism.core.utils import read_json, utc_now
def trait_distance(before, after):
    keys=sorted(set(before)|set(after))
    return 0.0 if not keys else math.sqrt(sum((float(after.get(k,0))-float(before.get(k,0)))**2 for k in keys)/len(keys))
def collect_metrics(tick_result, org_path, scenario):
    genome=read_json(org_path/"genome.json",{}); state=tick_result["state"]; birth=read_json(org_path/"memory"/"birth_snapshot.json",{})
    current=genome.get("traits",{}); social=read_json(org_path/"memory"/"social.json",{}); caps=read_json(org_path/"memory"/"substrate_capabilities.json",{}); smap=read_json(org_path/"memory"/"substrate_map.json",{})
    return {"ts":utc_now(),"scenario":scenario,"colony_tick":tick_result["colony_tick"],"organism_id":genome.get("organism_id"),"name":genome.get("organism_name"),"scenario_role":genome.get("scenario_role"),"lineage_id":genome.get("lineage_id"),"generation":genome.get("generation"),"identity_stable":state["identity_stable"],"energy":round(state["energy"],4),"health":round(state["health"],4),"stress":round(state["stress"],4),"focus":tick_result["focus"],"messages_received":state["last_received_messages"],"messages_sent":state["last_sent_messages"],"known_peers":len(social.get("known_organisms",{})) if isinstance(social,dict) else 0,"mutation_count":state["mutation_count"],"mutation_happened":bool(tick_result["mutation"].get("mutated")),"reproduction_count":state["reproduction_count"],"reflection_count":state["reflection_count"],"substrate_map_count":state.get("substrate_map_count",0),"immune_threat":tick_result["immune"]["threat"],"trait_drift":round(trait_distance(birth.get("genome",{}).get("traits",current), current),6),"traits":current,"hormones":state["hormones"],"substrate_os_family":caps.get("os_family"),"substrate_available_command_count":caps.get("available_command_count"),"substrate_visibility_score":smap.get("interpretation",{}).get("visibility_score"),"substrate_mapped_categories":smap.get("interpretation",{}).get("mapped_categories")}
